### ISSUE TITLE
Enhance submit votes button style for when it is submittable

### ISSUE THREAD

**Issue by V-ed** [V-ed/Scouts-Elections#72]
Currently, it is green and faded out when it is disabled. While this is neat enough for me, kids are kids, and they may not understand that they need to submit their votes using the dedicated button.

Therefore, I should make it gray when disabled, green when available and green faded away when submitting.

Also, to further improve discoverability, I should add a subtle animation of the button shrinking and growing when available to submit, with sometimes few "bell jiggles" animations just to take their eyes' attention.

**Comment by V-ed** [comment]
I've done a quick demo for an animation, here's my results :

```css
button {
  animation: available 6s;
  animation-iteration-count: infinite;
}

@keyframes available {
    0% { transform: scale(1); }
    5% { transform: scale(0.97); }
    10% { transform: scale(1.07); }
    15% { transform: scale(0.97); }
    20% { transform: scale(1.07); }
    25% { transform: scale(0.97); }
    30% { transform: scale(1.07); }
    35% { transform: scale(0.97); }
    40% { transform: scale(1.07); }
    45% { transform: scale(0.97); }
    50% { transform: scale(1.07); }
    55% { transform: scale(0.97); }
    60% { transform: scale(1.07); }
    65% { transform: scale(0.97); }
    70% { transform: scale(1.07); }
    75% { transform: scale(0.97); }
    80% { transform: scale(1.07); }
    85% { transform: scale(0.97); }
    90% { transform: scale(1) rotate(0deg); }
    92% { transform: scale(1) rotate(-2deg); }
    94% { transform: scale(1) rotate(2deg); }
    96% { transform: scale(1) rotate(-2deg); }
    98% { transform: scale(1) rotate(2deg); }
    100% { transform: scale(1) rotate(0deg); }
}
```
